# Generated by Django 3.0.2 on 2020-01-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60, verbose_name='автор')),
                ('code', models.TextField(blank=True, verbose_name='пример кода')),
                ('image', models.ImageField(upload_to='answer_img')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60, verbose_name='автор')),
                ('body', models.TextField(verbose_name='комментарий')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_self', to='questions.Comment')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
