# Generated by Django 3.0.3 on 2020-03-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200303_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='code',
            new_name='body',
        ),
    ]
