# Generated by Django 3.0.4 on 2020-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200322_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='лайки'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
