# Generated by Django 3.0.2 on 2020-01-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('author', models.CharField(max_length=50, verbose_name='автор')),
                ('description', models.TextField(verbose_name='описание')),
                ('year', models.SmallIntegerField(verbose_name='год')),
                ('href', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
                'ordering': ['title'],
            },
        ),
    ]
