# Generated by Django 3.0.3 on 2020-03-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200303_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_img', verbose_name='картинка'),
        ),
    ]
