# Generated by Django 3.0.3 on 2020-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.SlugField()),
                ('content', models.TextField(verbose_name='контент')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='создан')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='изменен')),
                ('status', models.IntegerField(choices=[(1, 'опубликован'), (0, 'черновик')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
            },
        ),
    ]
