# Generated by Django 3.0.2 on 2020-01-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='status',
            field=models.IntegerField(choices=[(1, 'опубликован'), (0, 'черновик')], default=0),
        ),
    ]
