# Generated by Django 3.0.2 on 2020-01-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forum', '0002_forumpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='картинка'),
        ),
    ]
